# Generated by Django 4.0.8 on 2022-11-08 14:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Add some alluring text here', max_length=512)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', max_length=50)),
                ('style', models.JSONField(default={'background_color': 'black', 'height': '100px', 'padding': '35px', 'text_align': 'center', 'text_color': 'white'})),
                ('pages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=124, null=True), default=['a', 'l', 'l'], size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
    ]
