# Generated by Django 4.0.8 on 2022-11-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='pages',
        ),
    ]
