# Generated by Django 4.0.8 on 2022-11-07 07:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_banner_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=124, null=True), default=['all'], size=None),
        ),
    ]
